In [5]:
import pandas as pd

template = pd.read_csv("omx_template.csv")
print(template.info())
template

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    5 non-null      object
 1   open    5 non-null      float64
 2   high    5 non-null      float64
 3   low     5 non-null      float64
 4   close   5 non-null      float64
 5   volume  5 non-null      int64
dtypes: float64(4), int64(1), object(1)
memory usage: 372.0+ bytes
None

         date    open    high     low   close   volume
0  2025-08-07  100.00  102.00   99.50  101.50  1000000
1  2025-08-08  101.50  103.25  100.75   99.75  1250000
2  2025-08-09   99.75  101.50   98.25  102.25   875000
3  2025-08-10  102.25  104.00  101.50  103.10  1500000
4  2025-08-11  103.10  105.50  102.75  104.85  1100000

In [11]:
omx30 = pd.read_csv("omxs30_original.csv")[
    ["Date", "Open", "High", "Low", "Close", "Volume"]
]

# Replace all commas with dots in the entire dataframe
omx30 = omx30.applymap(lambda x: x.replace(",", ".") if isinstance(x, str) else x)

omx30 = omx30.rename(
    columns={
        "Date": "date",
        "Open": "open",
        "High": "high",
        "Low": "low",
        "Close": "close",
        "Volume": "volume",
    }
)

# remove time-component from date
omx30["date"] = omx30["date"].str.split(" ").str[0]


print(omx30.info())
omx30.to_csv(
    "omxs30_cleaned.csv", index=False
)  # Save the cleaned data to a new CSV file
omx30

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1361 entries, 0 to 1360
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1361 non-null   object
 1   open    1361 non-null   object
 2   high    1361 non-null   object
 3   low     1361 non-null   object
 4   close   1361 non-null   object
 5   volume  1361 non-null   int64
dtypes: int64(1), object(5)
memory usage: 63.9+ KB
None

/var/folders/8d/zz072l3d0mv392k_mtqd_3tr0000gn/T/ipykernel_62733/3602131639.py:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  omx30 = omx30.applymap(lambda x: x.replace(",", ".") if isinstance(x, str) else x)

            date    open    high     low   close  volume
0     2020-01-02  682.86  693.83  682.86  693.56       0
1     2020-01-03  689.38  689.38  684.22   686.6       0
2     2020-01-07   686.8  692.03   686.5  689.23       0
3     2020-01-08  683.91  689.18  681.66  688.86       0
4     2020-01-09   693.7   693.7   690.3  691.76       0
...          ...     ...     ...     ...     ...     ...
1356  2025-08-05  967.59   969.7  964.11  966.65       0
1357  2025-08-06  971.21  974.83  964.35   966.1       0
1358  2025-08-07  969.04  980.14  969.04  976.67       0
1359  2025-08-08  978.67  981.35  976.41  978.73       0
1360  2025-08-11  980.73   981.3  973.44  973.59       0

[1361 rows x 6 columns]

In [ ]:
import yfinance as yf

ticker = yf.Ticker("LATO-B.ST")  # AAPL VOLV-B.ST
data = ticker.get_info()

data  # Display the keys of the data dictionary

{'address1': 'J A Wettergrens gata 7',
 'address2': 'PO Box 336',
 'city': 'Gothenburg',
 'zip': '401 25',
 'country': 'Sweden',
 'phone': '46 31 89 17 90',
 'fax': '46 31 45 60 63',
 'website': 'https://www.latour.se/sv',
 'industry': 'Conglomerates',
 'industryKey': 'conglomerates',
 'industryDisp': 'Conglomerates',
 'sector': 'Industrials',
 'sectorKey': 'industrials',
 'sectorDisp': 'Industrials',
 'longBusinessSummary': 'Investment AB Latour (publ) is an investment firm. The firm prefer to invest in companies for long term with Development, manufacture and marketing of proprietary products under their own brands. It prefer to invest in companies with 10 percent average annual growth over a business cycle, 10 percent operating margin over a business cycle, and 15 - 20 percent return on operating capital over a business cycle. It takes an active role on the board of its investee company. The firm was previously known as AB Hevea. Investment AB Latour (publ) was founded in 1984 and is based in Gothenburg, Sweden with an additional office in Malmo, Sweden and Stockholm, Sweden.',
 'fullTimeEmployees': 9000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Johan  Hjertonsson MBA',
   'age': 56,
   'title': 'President, CEO & Director',
   'yearBorn': 1968,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Mikael Johnsson Albrektsson',
   'title': 'Chief Financial Officer',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Helene  Mellquist',
   'age': 60,
   'title': 'Executive VP & COO',
   'yearBorn': 1964,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Johan  Menckel',
   'age': 53,
   'title': 'Executive VP & Chief Investment Officer',
   'yearBorn': 1971,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Fredrik  Lycke',
   'title': 'Investment Director',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Ida  Saalman',
   'title': 'Investment Director',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Fredrika  Ekman',
   'title': 'Investment Director',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Anders  ArdstÃ¥l',
   'title': 'Investment Director',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Jens  Synneby',
   'title': 'Investment Director',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 9,
 'boardRisk': 9,
 'compensationRisk': 7,
 'shareHolderRightsRisk': 10,
 'overallRisk': 10,
 'governanceEpochDate': 1754006400,
 'compensationAsOfEpochDate': 1735603200,
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 250.0,
 'open': 248.6,
 'dayLow': 246.1,
 'dayHigh': 250.5,
 'regularMarketPreviousClose': 250.0,
 'regularMarketOpen': 248.6,
 'regularMarketDayLow': 246.1,
 'regularMarketDayHigh': 250.5,
 'dividendRate': 4.6,
 'dividendYield': 1.84,
 'exDividendDate': 1746748800,
 'payoutRatio': 0.5277,
 'fiveYearAvgDividendYield': 1.3,
 'trailingPE': 31.801804,
 'volume': 176600,
 'regularMarketVolume': 176707,
 'averageVolume': 198696,
 'averageVolume10days': 148499,
 'averageDailyVolume10Day': 148499,
 'bid': 246.5,
 'ask': 246.6,
 'bidSize': 0,
 'askSize': 0,
 'marketCap': 157975478272,
 'fiftyTwoWeekLow': 230.0,
 'fiftyTwoWeekHigh': 327.0,
 'priceToSalesTrailing12Months': 5.8032284,
 'fiftyDayAverage': 249.792,
 'twoHundredDayAverage': 269.3245,
 'trailingAnnualDividendRate': 4.6,
 'trailingAnnualDividendYield': 0.0184,
 'currency': 'SEK',
 'tradeable': False,
 'enterpriseValue': 178688851968,
 'profitMargins': 0.17650999,
 'floatShares': 21915183,
 'sharesOutstanding': 591731968,
 'heldPercentInsiders': 0.77242,
 'heldPercentInstitutions': 0.084709994,
 'impliedSharesOutstanding': 639318016,
 'bookValue': 64.902,
 'priceToBook': 3.8072786,
 'lastFiscalYearEnd': 1735603200,
 'nextFiscalYearEnd': 1767139200,
 'mostRecentQuarter': 1751241600,
 'earningsQuarterlyGrowth': -0.108,
 'netIncomeToCommon': 4805000192,
 'trailingEps': 7.77,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1497916800,
 'enterpriseToRevenue': 6.564,
 'enterpriseToEbitda': 45.771,
 '52WeekChange': -0.15110356,
 'SandP52WeekChange': 0.14064062,
 'lastDividendValue': 4.6,
 'lastDividendDate': 1746748800,
 'quoteType': 'EQUITY',
 'currentPrice': 247.1,
 'targetHighPrice': 300.0,
 'targetLowPrice': 277.0,
 'targetMeanPrice': 288.5,
 'targetMedianPrice': 288.5,
 'recommendationMean': 2.33333,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 2,
 'totalCash': 2156000000,
 'totalCashPerShare': 3.372,
 'ebitda': 3904000000,
 'totalDebt': 20696000512,
 'quickRatio': 0.659,
 'currentRatio': 1.078,
 'totalRevenue': 27221999616,
 'debtToEquity': 49.493,
 'revenuePerShare': 42.579,
 'returnOnAssets': 0.03225,
 'returnOnEquity': 0.11474,
 'grossProfits': 10705000448,
 'freeCashflow': 713625024,
 'operatingCashflow': 3497999872,
 'earningsGrowth': -0.109,
 'revenueGrowth': 0.088,
 'grossMargins': 0.39325002,
 'ebitdaMargins': 0.14341,
 'operatingMargins': 0.1105,
 'financialCurrency': 'SEK',
 'symbol': 'LATO-B.ST',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'corporateActions': [],
 'regularMarketTime': 1755703775,
 'exchange': 'STO',
 'messageBoardId': 'finmb_2907922',
 'exchangeTimezoneName': 'Europe/Stockholm',
 'exchangeTimezoneShortName': 'CEST',
 'gmtOffSetMilliseconds': 7200000,
 'market': 'se_market',
 'esgPopulated': False,
 'regularMarketChangePercent': -1.1599976,
 'regularMarketPrice': 247.1,
 'fiftyDayAverageChange': -2.6920013,
 'fiftyDayAverageChangePercent': -0.0107769715,
 'twoHundredDayAverageChange': -22.224487,
 'twoHundredDayAverageChangePercent': -0.08251937,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '2.3 - Buy',
 'cryptoTradeable': False,
 'marketState': 'POSTPOST',
 'shortName': 'Latour, Investmentab. ser. B',
 'longName': 'Investment AB Latour (publ)',
 'hasPrePostMarketData': False,
 'firstTradeDateMilliseconds': 946886400000,
 'regularMarketChange': -2.899994,
 'regularMarketDayRange': '246.1 - 250.5',
 'fullExchangeName': 'Stockholm',
 'averageDailyVolume3Month': 198696,
 'fiftyTwoWeekLowChange': 17.100006,
 'fiftyTwoWeekLowChangePercent': 0.07434785,
 'fiftyTwoWeekRange': '230.0 - 327.0',
 'fiftyTwoWeekHighChange': -79.899994,
 'fiftyTwoWeekHighChangePercent': -0.24434249,
 'fiftyTwoWeekChangePercent': -15.110355,
 'earningsTimestamp': 1762270200,
 'earningsTimestampStart': 1762270200,
 'earningsTimestampEnd': 1762270200,
 'earningsCallTimestampStart': 1755590400,
 'earningsCallTimestampEnd': 1755590400,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 7.77,
 'trailingPegRatio': None}